char* tabela_textos[] PROGMEM = 
{
"",        // tabela_textos[0]
"MENU 1",  // tabela_textos[1]
"MENU 2",  // tabela_textos[2]
"HEURE ET DATE", // tabela_textos[3]
"TEST LED", // tabela_textos[4]
"REGLAGE GENERAL", // tabela_textos[5]
"GRAFIQUE", // tabela_textos[6]
"CONFIG LED", // tabela_textos[7]
"TPA AUTOMATIQUE", // tabela_textos[8] // Troca Parcial de Água automática.
"POMPE DOSEUSE", // tabela_textos[9]
"WAVEMAKER", // tabela_textos[10]
"SORTIE", // tabela_textos[11]
"REGLAGE HEURE ET DATE", // tabela_textos[12]
"SAUVE", // tabela_textos[13]
"HEURE:", // tabela_textos[14]
"DATE:", // tabela_textos[15]
"TEST LEDs", // tabela_textos[16]
"START", // tabela_textos[17]
"TEST", // tabela_textos[18]
"TEST LEDs",//tabela_textos[19]
"STOP", // tabela_textos[20]
"TESTE EM ANDAMENTO", // tabela_textos[21]
"TEMPO:", // tabela_textos[22]
"PUISSANCE DE SORTIE (0-255):", // tabela_textos[23]
"CONTROLE TEMPERATURE DE L'EAU", // tabela_textos[24]
"GRAPHIQUE TEMPERATURE", // tabela_textos[25]
"GRAPHIQUE REDOX", // tabela_textos[26]
"GRAPHIQUE PH AQUARIUM", // tabela_textos[27]
"GRAPHIQUE PH REACTEUR CALCIUM",// tabela_textos[28]
"GRAPHIQUE DENSITE",// tabela_textos[29]
"CHANGER LA PUISSANCE DES LED BLANCHE", // tabela_textos[30]
"CHANGER LA PUISSANCE DES LED BLEU", // tabela_textos[31]
"CONF. JOUR ET HEURE POUR TPA AUTOMATIQUE",// tabela_textos[32]
"CHANGER CONFIGURATION DES DOSAGES",// tabela_textos[33]
"CHOISIR UN GRAPHIQUE",// tabela_textos[34]
"WAVEMAKER", // tabela_textos[35]
"CHOISIR UN PARAMETRE", // tabela_textos[36]
"CONTROLE DU PH DU RAC", // tabela_textos[37]
"CONTROLE DU REDOX", // tabela_textos[38]
"CONTROLE PH AQUARIUM",// tabela_textos[39]
"CONTROLE DENSITE", // tabela_textos[40]
"CHOISIR UN DOSAGE", // tabela_textos[41]
"CALIBRER DOSAGE", // tabela_textos[42]
"DOSAGE MANUEL", // tabela_textos[43]
"CONFIGURER DOSAGE AUTOMATIQUE" ,// tabela_textos[44]
"CONFIGURER DOSAGE PERSONALISE", // tabela_textos[45]
"ENTRER LE MDP", // tabela_textos[46]
"CONFIGURER DOSAGE PERSONALISE", // tabela_textos[47]
"CHANGER LA CONFIGURATION DES DOSAGES", // tabela_textos[48]
"AFFICHER CONFIG DOSAGE AUTOMATIQUE", // tabela_textos[49]
"AFFICHER CONFIG DOSAGE PERSONALISE", // tabela_textos[50]
"DESACTIVER POMPE DOSEUSE", // tabela_textos[51]
"LUMIERE NOCTURNE   255 = 100 %", // tabela_textos[52]
"SELECTIONER UN TIMER", // tabela_textos[53]
"CONFIGURATION TIMER 1", // tabela_textos[54]
"CONFIGURATION TIMER 2", // tabela_textos[55]
"CONFIGURATION TIMER 3", // tabela_textos[56]
"CONFIGURATION TIMER 4", // tabela_textos[57]
"CONFIGURATION TIMER 5", // tabela_textos[58]
"LUNDI", // tabela_textos[59]
"MARDI", // tabela_textos[60]
"MERCREDI", // tabela_textos[61]
"JEUDI", // tabela_textos[62]
"VENDREDI", // tabela_textos[63]
"SAMEDI", // tabela_textos[64]
"DIMANCHE", // tabela_textos[65]
"RETOUR", // tabela_textos[66]
"NOUVELLE LUNE", // tabela_textos[67]
"LUNE MONTANTE", // tabela_textos[68]
"PLEINE LUNE",  // tabela_textos[69]
"L", // tabela_textos[70] // Segunda
"M",// tabela_textos[71] // Terça
"M", // tabela_textos[72] // Quarta
"D", // tabela_textos[73] // Dimanche
"CONSIGNE TEMPERATURE:", // tabela_textos[74]
"HYSTERESIS:", // tabela_textos[75]
"SEUIL D'ALARME:", // tabela_textos[76]
"PUISSANCE DES LED BLANCHE: 255 = 100%", // tabela_textos[77]
"BLEU", // tabela_textos[78]
"PUISSANCE DES LED BLEU: 255 = 100%", // tabela_textos[79]
"BLANC", // tabela_textos[80]
"REGALGE", // tabela_textos[81]
"SAUV EEPROM", // tabela_textos[82]
"HEURE:", // tabela_textos[83]
"DUREE MAXIMUM", // tabela_textos[84]
"PAS A PAS:", // tabela_textos[85]
"ECHEC!", // tabela_textos[86]
"NORMAL", // tabela_textos[87]
"MANUEL", // tabela_textos[88]
"AUTOMATIQUE", // tabela_textos[89]
"PERSONALISE", // tabela_textos[90]
"VOIR CONFIG.", // tabela_textos[91]
"DESATIVAR MODOS", // tabela_textos[92]
"TEMPERATURE", // tabela_textos[93]
"PH AQUARIUM", // tabela_textos[94]
"PH RAC", // tabela_textos[95]
"ORP", // tabela_textos[96]
"DENSITE", // tabela_textos[97]
"CALIBRER SONDES", // tabela_textos[98]
"CONSIGNE PH:", // tabela_textos[99]
"CONSIGNE ORP:", // tabela_textos[100]
"CONSIGNE DENSITE:", // tabela_textos[101]
"POMPE DOSEUSE 1", // tabela_textos[102]
"POMPE DOSEUSE 2", // tabela_textos[103]
"POMPE DOSEUSE 3", // tabela_textos[104]
"METTRE UN RECIPIENT SOUS LA SORTIE", // tabela_textos[105]
"ET CLIQUEZ SUR DEMARRER.", // tabela_textos[106]
"ENSUITE INSSEREZ LA VALEUR OBTENUE", // tabela_textos[107]
"EN ML DANS LE CHAMP CI-DESSOUS.", // tabela_textos[107]
"POUR DE MEILLEURS RESULTATS REFAIRE LE", // tabela_textos[109]
"TEST APRES UTTILISATION.", // tabela_textos[110]
"POMPE DOSEUSE 1 SELECTIONNEE", // tabela_textos[111]
"POMPE DOSEUSE 2 SELECTIONNEE",// tabela_textos[112]
"POMPE DOSEUSE 3 SELECTIONNEE", // tabela_textos[113]
"SELECTIONNER UN VOLUME A DOSER", // tabela_textos[114]
"EM ML DANS LE CHAMP CI-DESSOUS", // tabela_textos[115]
"ENSUITE CLIQUEZ SUR DEMARRER.", // tabela_textos[116]
"LE DOSAGE DEMARRERA DANS 10 SEC",// tabela_textos[117]
"DEBUT:", // tabela_textos[118]
"FIN:", // tabela_textos[119]
"SELECTION ", // tabela_textos[120]
"VOLUME ", // tabela_textos[121]
"(ML/JOUR):",  // tabela_textos[122]
"NOMBRE",  // tabela_textos[123]
"DE DOSES:",  // tabela_textos[124]
"SELECTIONEE", // tabela_textos[125]
"ON", // tabela_textos[126]
"OFF", // tabela_textos[127]
"QUANTITEE DE DOSES:", // tabela_textos[128]
"POMPE DOSEUSE 1:", // tabela_textos[129]
"POMPE DOSEUSE 2:", // tabela_textos[130]
"POMPE DOSEUSE 3:", // tabela_textos[131]
"LUNE DECROISSANTE", // tabela_textos[132]
"CALIBRER", // tabela_textos[133]
"DESACTIVATION", // tabela_textos[134]
"SUIVANT", // tabela_textos[135]
"RAZ", // tabela_textos[136]
"VALIDEZ", // tabela_textos[137]
"PRECEDENT", // tabela_textos[138]
"AUTOMATIQUE", // tabela_textos[139]
"PERSONALISE", // tabela_textos[140]
"UTILISER", // tabela_textos[141]
"CETTE ", // tabela_textos[142]
"FONCTION", // tabela_textos[143]
"SEULEMENT POUR", // tabela_textos[144]
"DESACTIVER MODES", // tabela_textos[145]
"DE DOSAGE.", // tabela_textos[146]
"ACTIVATION", // tabela_textos[147]
"DESACTIVATION", // tabela_textos[148]
"DENSITE", // tabela_textos[149]
"DESACTIVATION ", // tabela_textos[150]
"CE:", // tabela_textos[151]
"DESACTIVER", // tabela_textos[152]
"ACTIVATION OU", // tabela_textos[153]
"DE LA POMPE", // tabela_textos[154]
"DE DOSAGE:", // tabela_textos[155]
"ECLAIRAGE MINIMUM:", // tabela_textos[156]
"PLEINE LUNE:", // tabela_textos[157]
"NOUVELLE LUNE:", //  tabela_textos[158]
"ECLAIRAGE LUNAIRE", // tabela_textos[159]
"TIMERS", // tabela_textos[160]
"DEPART TIMER", // tabela_textos[161]
"ARRET TIMER", // tabela_textos[162]
"PARAMETRE!", // tabela_textos[163]
"MODE MANUEL SELECTIONE", // tabela_textos[164]
"MODE AUTOMATIQUE SELECTIONE", // tabela_textos[165]
"INTERVALE ", // tabela_textos[166]
"ERREUR!", // tabela_textos[167]
"HEURE FIN", // tabela_textos[168]
"ERREUR!", // tabela_textos[169]
"HEURE", // tabela_textos[170]
"MODE PERSONALISE SELECTIONE", // tabela_textos[171]
"MODE CALIBRATION SELECTIONE",  // tabela_textos[172]
"PASSE CORRECT", // tabela_textos[173]
"PASSE INCORRECT!", // tabela_textos[174]
"MAXI 6 CHIFFRES!", // tabela_textos[175]
"INTERVALLE ENTRE DEBUT ET FIN", // tabela_textos[176]
"DOIT ETRE AU MOINS DIX MINUTES!", // tabela_textos[177]
"L'HEURE DE FIN PEUT ETRE INFERIEUR", // tabela_textos[178]
"QUE A INICIAL!",// tabela_textos[179]
"PUISSANCE MAXI:", // tabela_textos[180]
"% ILLUMINE", // tabela_textos[181]
"PHASE LUNAIRE:", // tabela_textos[182]
"T.RAMPE:", // tabela_textos[183]
"TEMP. EAU:", // tabela_textos[184]
"PH AQUARIUM:",  // tabela_textos[185]
"PH RAC:",  // tabela_textos[186]
"DENSITE:", // tabela_textos[187]
"ORP:", // tabela_textos[188]
"GR FROID:", // tabela_textos[189]
"CHAUFFAGE:", // tabela_textos[190]
"RAC:", // tabela_textos[191]
"OZONIS:", // tabela_textos[192]
"REPOSICAO:", // tabela_textos[193]
"NIVEAU:", // tabela_textos[194]
"TPA:", // tabela_textos[195]
"BAS!", // tabela_textos[196]
"NORMAL", // tabela_textos[197]
"J", // tabela_textos[198] // Quinta
"V", //  tabela_textos[199] // Sexta 
"S", // tabela_textos[200] // Sábado
"CONFIG. LEDS",// tabela_textos[201]
"CONFIGURATION LEDS", // tabela_textos[202]
"SELECTIONER UNE PERIODE." // tabela_textos[203]
};
